name: paper_ai
description: "An AI assistant for e-ink devices"

publish_to: 'none'
version: 0.0.3+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  anthropic_sdk_dart: ^0.1.0
  collection: ^1.18.0
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.4+1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  langchain: ^0.7.7+1
  langchain_anthropic: ^0.1.1+2
  langchain_google: ^0.6.4+1
  langchain_openai: ^0.7.2+3
  path: ^1.9.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - .env